### ISSUE TITLE
Could You Add a Development Brach to Repo

### ISSUE THREAD

**Issue by abetancort** [Shadow00Caster/PlexAutoFileManager#3]
If possible add a **development branch** to **Repo** in order to be able to _add functionalities, test and debug_ without disrupting the **master brach** or **production version**. 

This would allow that modifications, mainly in code, to be only committed to the **master branch** when thoroughly reviewed, tested and cleared while still retaining a _consolidated code base_ in the **development branch** of the main **Repo**, and not just in its **forks**.

**Comment by Shadow00Caster** [comment]
Done, added you as colab as well.

**Comment by abetancort** [comment]
Thanks.
